### ISSUE TITLE
Drop `clock_gettime` implementation in favor of upstream

### ISSUE THREAD

**Issue by ian-h-chamberlain** [rust3ds/rust-linker-fix-3ds#13]
It looks like `libctru` has implemented the `clock_gettime` syscall now: https://github.com/devkitPro/libctru/commit/813d28ddc4155a0cd625577480aa2908ad07c706

As much as I prefer to have things implemented in Rust, it's probably best if we defer stuff like this to the canonical implementation upstream and reduce the surface area of this crate. We'll have to wait for a new release of `libctru` (which means we probably also should document some minimum required version of `libctru` somewhere...)

**Comment by ian-h-chamberlain** [comment]
No, it hasn't been released yet, so I think we can just leave this open to track it until a new release happens.

**Comment by Meziu** [comment]
Closed with #15
