### ISSUE TITLE
Move subprocess API stubs here instead of ctru-rs

### ISSUE THREAD

**Issue by ian-h-chamberlain** [rust3ds/rust-linker-fix-3ds#18]
I think this crate makes more sense for the stubs we have in `ctru-rs`' test runner:

https://github.com/rust3ds/ctru-rs/blob/master/ctru-rs/src/test_runner.rs#L82-L100

That particular case was a quick fix since nothing linked those symbols before we added `extern crate test`, but they could prove useful for other cases too.

Obviously this would result in duplicate symbols briefly so we would need to make the change simultaneously here and remove there for it to work.

**Comment by Meziu** [comment]
Yes, now that we can, we should. You can open 2 PRs and we’ll just merge them simultaneously.
